### ISSUE TITLE
K8s v1.16 got error

### ISSUE THREAD

**Issue by EduardoFiorentini** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#50]
Hello!
I've got error message while trying to deploy in K8s v1.16 :
kubectl create -f cassandra-statefulset.yaml
error: unable to recognize cassandra-statefulset.yaml: no matches for kind "StatefulSet" in version "apps/v1beta1".

After trying to change to apiVersion: "apps/v1" error message also changes:
error: error validating cassandra-statefulset.yaml: error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by andrew-aernos** [comment]
Add the selector field in the cassandra-statefulset.yaml
```
---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
      ...

```
