### ISSUE TITLE
Not working on k8s v1.21.0

### ISSUE THREAD

**Issue by bhsrinivasan-px** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#52]
I think the stateful set needs to be updated, in order to run on k8s versions 1.21.0 and above

```
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
...
...
```
